server:
  port: 5000
spring:
  application:
    name: WebPoll
  jpa:
    database: sql_server
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:sqlserver://192.168.99.100:1433;databaseName=WebPoll
    username: sa
    password: saWasHere??01
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver